'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
package org.eclipse.keyple #FFFFFF {
  package core #FFFFFF {
    package seproxy #FFFFFF {

      !include ../../../KeypleCoreApi/ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_SELECTOR_AID
      !include ../../../KeypleCoreApi/ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_SELECTOR_0_8

      SeSelector +-up- AidSelector
      SeSelector "1" o-up- "0..1" AidSelector
    }

    package selection #FFFFFF {
      !include ../../../KeypleCoreApi/ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-Selection-ClassElements.iuml!SELECTION_SELECTION
      !include ../../../KeypleCoreApi/ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-Selection-ClassElements.iuml!SELECTION_REQUEST_0_8
      !include ../../../KeypleCoreApi/ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-Selection-ClassElements.iuml!SELECTION_RESOURCE_0_8

      AbstractSeSelectionRequest -down- AbstractMatchingSe : selects >
      SeSelection "1" o-up- "*" AbstractSeSelectionRequest
      SeResource_T "1" *-up- "1" AbstractMatchingSe
    }

    AbstractSeSelectionRequest "1" o-up- "1" SeSelector
  }

  package calypso.transaction #FFFFFF {
    !include KeypleCalypso-ApplicationApi-ClassDiag-Transaction-ClassElements.iuml!TRANSACTION_INVALIDATED
    !include KeypleCalypso-ApplicationApi-ClassDiag-Transaction-ClassElements.iuml!TRANSACTION_PO_SHORT
    !include KeypleCalypso-ApplicationApi-ClassDiag-Transaction-ClassElements.iuml!TRANSACTION_SELECTION_0_8

    PoAidSelector "1" *-left- "1" InvalidatedPo
    InvalidatedPo --+ PoSelector

    PoSelector +-up- PoAidSelector
    PoSelector "1" o-up- "0..1" PoAidSelector
    PoSelectionRequest "1" o-up- "1" PoSelector
    PoSelectionRequest -down- CalypsoPo : selects >
    PoResource "1" *-up- "1" CalypsoPo
  }

  PoAidSelector -left-|> AidSelector : extends
  PoSelector -left-|> SeSelector : extends
  PoSelectionRequest -left-|> AbstractSeSelectionRequest : extends
  CalypsoPo -left-|> AbstractMatchingSe : extends
  PoResource -left-|> SeResource_T : extends
}
@enduml
