'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
package org.eclipse.keyple.seproxy #FFFFFF {

  !include ../../ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_SELECTOR_0_8
  !include ../../ApplicationApi/puml/KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_CHANNEL

  package message #FFFFFF {
'together {
    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_PROXYREADER_0_8
    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_SEREQUEST_0_8
'}
    !include KeypleCore-PluginApi-ClassDiag-SE_Proxy-ClassElements.iuml!MESSAGE_APDUREQUEST

    ProxyReader "0..1" -up- "+" SeRequest : sends >
    ProxyReader "0..1" -down- "+" SeResponse : receives >
    SeRequest "0..1" o-right-> "*" ApduRequest : apduRequests
    SeResponse "0..1" o-right-> "*" ApduResponse : apduResponses
  }

  SeSelector -right- SeRequest
  ChannelControl -right- ProxyReader
}

'SeRequest -- SeSelector : SE Protocol Flag
'ProxyReader -right- SeProtocol : SE Protocol Settings
SeProtocol -right[hidden]- ApduRequest
@enduml