'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
together {
  package external.terminalapplication #3399FF {
    class SpecificTerminal
  }

  !include KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_COMPARABLE_0_8
}

package org.eclipse.keyple.core.seproxy #FFFFFF {
  !include KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_SERVICE_0_8
  !include KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_POOLPLUGIN
  !include KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_PLUGIN_0_8
  !include KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_READER

  SeProxyService "1" *-down-> "*" ReaderPlugin : plugins
  ReaderPlugin <|-left- ReaderPoolPlugin : extends
  ReaderPlugin "1" *-right-> "*" SeReader : readers
}

SpecificTerminal -down-> SeProxyService : uses >

!include KeypleCore-ApplicationApi-ClassDiag-SE_Proxy-ClassElements.iuml!SEPROXY_UTIL
Nameable <|-up- ReaderPlugin : extends
Nameable <|-- SeReader : extends
Configurable <|-up- ReaderPlugin : extends
Configurable <|-- SeReader : extends

Comparable <|-- ReaderPlugin : extends
Comparable <|-- SeReader : extends
@enduml
