'---------------------------------------------------------------------------------
' Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Eclipse Public License 2.0 which is available at
' http://www.eclipse.org/legal/epl-2.0
'
' SPDX-License-Identifier: EPL-2.0 4
'---------------------------------------------------------------------------------

@startuml
package org.keyple.calypso.transaction #FFFFFF {

  +class PoResource {
    +PoResource(<color:red>SeReader seReader</color>,
    CalypsoPo calypsoPo);
  }

  +class "<b>final</b> CalypsoPo" as CalypsoPo {
    ~CalypsoPo(<color:red>SeResponse selectionResponse</color>)

    +String getDfName()
    +String getApplicationSerialNumber()
    +String getStartupInfo()

    +<color:royalBlue><b><i>boolean is_Xxx()</i></b></color>

    +<color:royalBlue><b><i>Xxx getData_Xxx()</i></b></color>
  }

  +class "<b>final</b> PoSecuritySetting" as PoSecuritySetting {
  }

  +class PoTransaction {
    +PoTransaction(PoResource poResource, PoSecuritySetting[0..1] securitySetting)

    +<color:royalBlue><b><i>prepareCommand_Xxx()</i></b></color>

    +<color:royalBlue><b><i>boolean processCommands_Xxx()</i></b></color>

    +<color:royalBlue><b><i>Xxx_SecureData getXxx_SecureData()</i></b></color>
  }

  PoResource -right[hidden]- PoSecuritySetting
  PoTransaction "1" o-up- "1" PoResource
  PoTransaction "1" o-up- "0..1" PoSecuritySetting
  PoResource "1" o-down- "1" CalypsoPo
  'CalypsoPo -[hidden]right--> PoTransaction
}
@enduml
